### ISSUE TITLE
Broken(?) submodule

### ISSUE THREAD

**Issue by wjk** [PowerShell/MMI#30]
This repository includes a submodule pointing to `git@github.com:PowerShell/omi`. Either this is a private repository, or the repo URL is out of date and needs to be corrected. Either way, `git clone --recursive` will fail when called on this repository. Could this please be rectified? Thanks!

**Comment by adityapatwardhan** [comment]
#37 Removed submodules

**Comment by KalleOlaviNiemitalo** [comment]
Should then remove `.gitmodules` as well.
